entity item
Ossama9/Tp-tests pull request #1
Opened 2023-05-24 08:59 UTC by Ayman-BEDDA

2023-05-24 16:56 UTC, Ossama9 approved these changes

2023-05-24 16:56 UTC, Ossama9 commented on Entities/Item.js
> +    }
```suggestion
    isValidNameItem(){  
        return this.name.length < 1000
    }
```

2023-05-24 17:03 UTC, Ossama9 requested changes

2023-05-24 17:03 UTC, Ossama9 commented on Entities/Item.js
> +        if (this.isValidItem()){
```suggestion
        if (this.isValidNameItem()){
```

2023-05-24 17:03 UTC, Ossama9 commented on Entities/Item.js
> +            return this
```suggestion
            return JSON.stringify(this)
```

2023-05-24 17:08 UTC, Ayman-BEDDA commented on Entities/Item.js
> +            return this
ça return automatiquement un json

2023-05-24 17:16 UTC, Ayman-BEDDA commented on Entities/Item.js
> +        if (this.isValidItem()){
Je vais laisser isValidItem parce que je vais vérifier aussi si il y a des propriétés vides

2023-05-24 17:22 UTC, Ossama9 commented on Entities/Item.js
> +        if (this.isValidItem()){
Ok

2023-05-25 06:40 UTC, Ossama9 approved these changes

2023-05-25 06:40 UTC, merged